#!/bin/bash

# /etc/init.d/sample.py
### BEGIN INIT INFO
# Provides:          shut-down
# Required-Start:    $remote_fs $syslog $network $time
# Required-Stop:     $remote_fs $syslog $network $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: watch for shutdown (external power removed)
# Description:       watch for shutdown (external power removed)
### END INIT INFO


function start() {
	/home/pi/rpi-pi-star-addons/shutdown.py \
	>> /home/pi/shutdown.log &
	echo $! > /home/pi/shutdown.pid
}

function stop() {
	pid=$(cat /home/pi/shutdown.pid)
	kill $pid
	sleep 10
	if [ -e /proc/$pid ]; then
		kill -9 $pid
		sleep 5
	fi
}

cmd=$1
shift
case $cmd in
	start) start $@ ;;
	stop) stop $@ ;;
	restart) stop $@ && start $@ ;;
esac
